<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251226115021 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Création des tables appointment, appointment_option, customer, formula, formula_item, seance, seance_option, seance_variant, user';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appointment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id INT NOT NULL, seance_variant_id INT DEFAULT NULL, formula_item_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE38F8449395C3F3 ON appointment (customer_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844313735CA ON appointment (seance_variant_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844DB8EEE2 ON appointment (formula_item_id)');
        $this->addSql('CREATE TABLE appointment_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, appointment_id INT DEFAULT NULL, seance_option_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1DD8BFFEE5B533F9 ON appointment_option (appointment_id)');
        $this->addSql('CREATE INDEX IDX_1DD8BFFEF9F65FE1 ON appointment_option (seance_option_id)');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE formula (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, price DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE formula_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT DEFAULT NULL, formula_id INT NOT NULL, seance_variant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CF1499ADA50A6386 ON formula_item (formula_id)');
        $this->addSql('CREATE INDEX IDX_CF1499AD313735CA ON formula_item (seance_variant_id)');
        $this->addSql('CREATE TABLE seance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE seance_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, extra_time_minutes INT NOT NULL, extra_price INT NOT NULL, seance_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_25F31B18E3797A94 ON seance_option (seance_id)');
        $this->addSql('CREATE TABLE seance_variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, duration_minutes INT NOT NULL, base_price INT NOT NULL, seance_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2931E16CE3797A94 ON seance_variant (seance_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F8449395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844313735CA FOREIGN KEY (seance_variant_id) REFERENCES seance_variant (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844DB8EEE2 FOREIGN KEY (formula_item_id) REFERENCES formula_item (id)');
        $this->addSql('ALTER TABLE appointment_option ADD CONSTRAINT FK_1DD8BFFEE5B533F9 FOREIGN KEY (appointment_id) REFERENCES appointment (id)');
        $this->addSql('ALTER TABLE appointment_option ADD CONSTRAINT FK_1DD8BFFEF9F65FE1 FOREIGN KEY (seance_option_id) REFERENCES seance_option (id)');
        $this->addSql('ALTER TABLE formula_item ADD CONSTRAINT FK_CF1499ADA50A6386 FOREIGN KEY (formula_id) REFERENCES formula (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE formula_item ADD CONSTRAINT FK_CF1499AD313735CA FOREIGN KEY (seance_variant_id) REFERENCES seance_variant (id)');
        $this->addSql('ALTER TABLE seance_option ADD CONSTRAINT FK_25F31B18E3797A94 FOREIGN KEY (seance_id) REFERENCES seance (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE seance_variant ADD CONSTRAINT FK_2931E16CE3797A94 FOREIGN KEY (seance_id) REFERENCES seance (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F8449395C3F3');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844313735CA');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844DB8EEE2');
        $this->addSql('ALTER TABLE appointment_option DROP CONSTRAINT FK_1DD8BFFEE5B533F9');
        $this->addSql('ALTER TABLE appointment_option DROP CONSTRAINT FK_1DD8BFFEF9F65FE1');
        $this->addSql('ALTER TABLE formula_item DROP CONSTRAINT FK_CF1499ADA50A6386');
        $this->addSql('ALTER TABLE formula_item DROP CONSTRAINT FK_CF1499AD313735CA');
        $this->addSql('ALTER TABLE seance_option DROP CONSTRAINT FK_25F31B18E3797A94');
        $this->addSql('ALTER TABLE seance_variant DROP CONSTRAINT FK_2931E16CE3797A94');
        $this->addSql('DROP TABLE appointment');
        $this->addSql('DROP TABLE appointment_option');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE formula');
        $this->addSql('DROP TABLE formula_item');
        $this->addSql('DROP TABLE seance');
        $this->addSql('DROP TABLE seance_option');
        $this->addSql('DROP TABLE seance_variant');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
