<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251228150455 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create a new table for payments and for giftcard';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE gift_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, recipient_name VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, message TEXT DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_used BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchaser_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E4696A8EED255ED6 ON gift_card (purchaser_id)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount DOUBLE PRECISION NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, method VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, gift_card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6D28840D2696A98F ON payment (gift_card_id)');
        $this->addSql('ALTER TABLE gift_card ADD CONSTRAINT FK_E4696A8EED255ED6 FOREIGN KEY (purchaser_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D2696A98F FOREIGN KEY (gift_card_id) REFERENCES gift_card (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE gift_card DROP CONSTRAINT FK_E4696A8EED255ED6');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D2696A98F');
        $this->addSql('DROP TABLE gift_card');
        $this->addSql('DROP TABLE payment');
    }
}
